import {
  countGuestsBySmartGroup,
  isWithinDaysUtc,
} from "@/lib/operatorGuests/smartGroupPredicates"
import type {
  GuestFeedbackSentiment,
  GuestMarketingStatusLabel,
  OperatorGuestFixture,
} from "@/types/operatorGuests"

/** Stable reference instant for fixture timestamps and tests. */
export const OPERATOR_GUEST_FIXTURES_REFERENCE_MS = Date.parse(
  "2026-07-21T12:00:00.000Z"
)

const LOCATIONS = [
  "Camden Street",
  "Shoreditch High St",
  "Manchester Deansgate",
  "Brighton Lanes",
] as const

type GuestSeed = {
  name: string
  email: string
  mobile: string | null
  marketingStatusLabel: GuestMarketingStatusLabel
  locationIndex: number
  capturedDaysAgo: number
  needsRecovery: boolean
  latestFeedbackSentiment: GuestFeedbackSentiment
  feedbackSubmissionCount: number
  hasOffer: boolean
  offerRedeemedDaysAgo: number | null
  lastInteractionDaysAgo: number | null
}

function daysAgoIso(daysAgo: number, referenceMs: number): string {
  return new Date(referenceMs - daysAgo * 24 * 60 * 60 * 1000).toISOString()
}

function marketingEligible(label: GuestMarketingStatusLabel): boolean {
  return label.startsWith("Eligible —")
}

function buildGuestFromSeed(
  index: number,
  seed: GuestSeed,
  referenceMs: number
): OperatorGuestFixture {
  const id = `guest-${String(index + 1).padStart(3, "0")}`

  return {
    id,
    name: seed.name,
    email: seed.email,
    mobile: seed.mobile,
    marketingStatusLabel: seed.marketingStatusLabel,
    marketingEligible: marketingEligible(seed.marketingStatusLabel),
    locationName: LOCATIONS[seed.locationIndex],
    capturedAt: daysAgoIso(seed.capturedDaysAgo, referenceMs),
    needsRecovery: seed.needsRecovery,
    latestFeedbackSentiment: seed.latestFeedbackSentiment,
    feedbackSubmissionCount: seed.feedbackSubmissionCount,
    hasOffer: seed.hasOffer,
    offerRedeemedAt:
      seed.offerRedeemedDaysAgo == null
        ? null
        : daysAgoIso(seed.offerRedeemedDaysAgo, referenceMs),
    lastInteractionAt:
      seed.lastInteractionDaysAgo == null
        ? null
        : daysAgoIso(seed.lastInteractionDaysAgo, referenceMs),
    lastInteractionLabel: "Feedback submitted",
  }
}

const GUEST_SEEDS: GuestSeed[] = [
  {
    name: "Amelia Hughes",
    email: "amelia.hughes@example.com",
    mobile: "+447700900101",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 0,
    capturedDaysAgo: 2,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 3,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 0,
  },
  {
    name: "Ben Clarke",
    email: "ben.clarke@example.com",
    mobile: "+447700900102",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 1,
    capturedDaysAgo: 4,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 1,
  },
  {
    name: "Chloe Bennett",
    email: "chloe.bennett@example.com",
    mobile: null,
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 0,
    capturedDaysAgo: 5,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 4,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 2,
  },
  {
    name: "Daniel Wright",
    email: "daniel.wright@example.com",
    mobile: "+447700900104",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 6,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 3,
  },
  {
    name: "Ella Morgan",
    email: "ella.morgan@example.com",
    mobile: "+447700900105",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 3,
    capturedDaysAgo: 8,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 4,
  },
  {
    name: "Finn O'Connor",
    email: "finn.oconnor@example.com",
    mobile: "+447700900106",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 10,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 5,
  },
  {
    name: "Grace Patel",
    email: "grace.patel@example.com",
    mobile: "+447700900107",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 0,
    capturedDaysAgo: 12,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 3,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 6,
  },
  {
    name: "Henry Lewis",
    email: "henry.lewis@example.com",
    mobile: "+447700900108",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 2,
    capturedDaysAgo: 13,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 7,
  },
  {
    name: "Isla Fraser",
    email: "isla.fraser@example.com",
    mobile: "+447700900109",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 3,
    capturedDaysAgo: 3,
    needsRecovery: true,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 1,
  },
  {
    name: "Jack Morrison",
    email: "jack.morrison@example.com",
    mobile: "+447700900110",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 7,
    needsRecovery: true,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 3,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 2,
  },
  {
    name: "Kate Sullivan",
    email: "kate.sullivan@example.com",
    mobile: "+447700900111",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 0,
    capturedDaysAgo: 9,
    needsRecovery: true,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 5,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 3,
  },
  {
    name: "Leo Ahmed",
    email: "leo.ahmed@example.com",
    mobile: "+447700900112",
    marketingStatusLabel: "Not eligible",
    locationIndex: 2,
    capturedDaysAgo: 11,
    needsRecovery: true,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 4,
  },
  {
    name: "Mia Robertson",
    email: "mia.robertson@example.com",
    mobile: "+447700900113",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 3,
    capturedDaysAgo: 14,
    needsRecovery: true,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 5,
  },
  {
    name: "Noah Campbell",
    email: "noah.campbell@example.com",
    mobile: "+447700900114",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 15,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 4,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 8,
  },
  {
    name: "Olivia Shaw",
    email: "olivia.shaw@example.com",
    mobile: "+447700900115",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 0,
    capturedDaysAgo: 16,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 9,
  },
  {
    name: "Parker Ellis",
    email: "parker.ellis@example.com",
    mobile: "+447700900116",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 18,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 1,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 10,
  },
  {
    name: "Quinn Davies",
    email: "quinn.davies@example.com",
    mobile: "+447700900117",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 3,
    capturedDaysAgo: 20,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 3,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 11,
  },
  {
    name: "Ruby Fletcher",
    email: "ruby.fletcher@example.com",
    mobile: "+447700900118",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 1,
    capturedDaysAgo: 22,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 12,
  },
  {
    name: "Samuel Green",
    email: "samuel.green@example.com",
    mobile: "+447700900119",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 0,
    capturedDaysAgo: 24,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 1,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 13,
  },
  {
    name: "Tara Singh",
    email: "tara.singh@example.com",
    mobile: "+447700900120",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 26,
    needsRecovery: false,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 2,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 14,
  },
  {
    name: "Umar Khan",
    email: "umar.khan@example.com",
    mobile: "+447700900121",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 3,
    capturedDaysAgo: 28,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 3,
    hasOffer: true,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 15,
  },
  {
    name: "Violet Harper",
    email: "violet.harper@example.com",
    mobile: "+447700900122",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 17,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: true,
    offerRedeemedDaysAgo: 3,
    lastInteractionDaysAgo: 3,
  },
  {
    name: "William Price",
    email: "william.price@example.com",
    mobile: "+447700900123",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 0,
    capturedDaysAgo: 19,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 2,
    hasOffer: true,
    offerRedeemedDaysAgo: 5,
    lastInteractionDaysAgo: 5,
  },
  {
    name: "Xander Cole",
    email: "xander.cole@example.com",
    mobile: "+447700900124",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 2,
    capturedDaysAgo: 21,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 4,
    hasOffer: true,
    offerRedeemedDaysAgo: 7,
    lastInteractionDaysAgo: 7,
  },
  {
    name: "Yasmin Ali",
    email: "yasmin.ali@example.com",
    mobile: "+447700900125",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 3,
    capturedDaysAgo: 23,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: true,
    offerRedeemedDaysAgo: 9,
    lastInteractionDaysAgo: 9,
  },
  {
    name: "Zara Mitchell",
    email: "zara.mitchell@example.com",
    mobile: "+447700900126",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 25,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 95,
  },
  {
    name: "Aaron Brooks",
    email: "aaron.brooks@example.com",
    mobile: "+447700900127",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 0,
    capturedDaysAgo: 40,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 3,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 100,
  },
  {
    name: "Bella Cooper",
    email: "bella.cooper@example.com",
    mobile: "+447700900128",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 55,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 110,
  },
  {
    name: "Callum Reid",
    email: "callum.reid@example.com",
    mobile: "+447700900129",
    marketingStatusLabel: "Not eligible",
    locationIndex: 3,
    capturedDaysAgo: 70,
    needsRecovery: false,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 120,
  },
  {
    name: "Daisy Powell",
    email: "daisy.powell@example.com",
    mobile: "+447700900130",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 29,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 16,
  },
  {
    name: "Ethan Ward",
    email: "ethan.ward@example.com",
    mobile: "+447700900131",
    marketingStatusLabel: "Suppressed",
    locationIndex: 0,
    capturedDaysAgo: 35,
    needsRecovery: false,
    latestFeedbackSentiment: "none",
    feedbackSubmissionCount: 0,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: null,
  },
  {
    name: "Freya Hunter",
    email: "freya.hunter@example.com",
    mobile: "+447700900132",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 45,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 20,
  },
  {
    name: "George Turner",
    email: "george.turner@example.com",
    mobile: "+447700900133",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 3,
    capturedDaysAgo: 50,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 25,
  },
  {
    name: "Hannah Fox",
    email: "hannah.fox@example.com",
    mobile: "+447700900134",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 60,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 30,
  },
  {
    name: "Isaac Palmer",
    email: "isaac.palmer@example.com",
    mobile: "+447700900135",
    marketingStatusLabel: "Not eligible",
    locationIndex: 0,
    capturedDaysAgo: 65,
    needsRecovery: false,
    latestFeedbackSentiment: "negative",
    feedbackSubmissionCount: 3,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 35,
  },
  {
    name: "Jasmine Reed",
    email: "jasmine.reed@example.com",
    mobile: "+447700900136",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 75,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 1,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 40,
  },
  {
    name: "Kian Brooks",
    email: "kian.brooks@example.com",
    mobile: "+447700900137",
    marketingStatusLabel: "Eligible — SMS",
    locationIndex: 3,
    capturedDaysAgo: 80,
    needsRecovery: false,
    latestFeedbackSentiment: "neutral",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 45,
  },
  {
    name: "Lily Grant",
    email: "lily.grant@example.com",
    mobile: "+447700900138",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 1,
    capturedDaysAgo: 85,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 4,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 50,
  },
  {
    name: "Max Fowler",
    email: "max.fowler@example.com",
    mobile: "+447700900139",
    marketingStatusLabel: "Suppressed",
    locationIndex: 0,
    capturedDaysAgo: 90,
    needsRecovery: false,
    latestFeedbackSentiment: "none",
    feedbackSubmissionCount: 0,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: null,
  },
  {
    name: "Nora Blake",
    email: "nora.blake@example.com",
    mobile: "+447700900140",
    marketingStatusLabel: "Eligible — Email",
    locationIndex: 2,
    capturedDaysAgo: 95,
    needsRecovery: false,
    latestFeedbackSentiment: "positive",
    feedbackSubmissionCount: 2,
    hasOffer: false,
    offerRedeemedDaysAgo: null,
    lastInteractionDaysAgo: 55,
  },
]

export function createOperatorGuestFixtures(
  referenceMs: number = OPERATOR_GUEST_FIXTURES_REFERENCE_MS
): OperatorGuestFixture[] {
  return GUEST_SEEDS.map((seed, index) =>
    buildGuestFromSeed(index, seed, referenceMs)
  )
}

export const OPERATOR_GUEST_FIXTURES = createOperatorGuestFixtures()

export type GuestFixtureCoverageMinimums = {
  newGuests: number
  needsRecovery: number
  positiveFeedback: number
  offerNotRedeemed: number
  recentRedeemers: number
  dormantGuests: number
  newThisMonth: number
  marketingEligible: number
}

export function assertGuestFixtureCoverageMinimums(
  guests: OperatorGuestFixture[],
  nowMs: number,
  minimums: GuestFixtureCoverageMinimums
): void {
  const counts = {
    newGuests: countGuestsBySmartGroup(guests, "new-guests", nowMs),
    needsRecovery: countGuestsBySmartGroup(guests, "needs-recovery", nowMs),
    positiveFeedback: countGuestsBySmartGroup(guests, "positive-feedback", nowMs),
    offerNotRedeemed: countGuestsBySmartGroup(
      guests,
      "offer-not-redeemed",
      nowMs
    ),
    recentRedeemers: countGuestsBySmartGroup(guests, "recent-redeemers", nowMs),
    dormantGuests: countGuestsBySmartGroup(guests, "dormant-guests", nowMs),
    newThisMonth: guests.filter((guest) =>
      isWithinDaysUtc(guest.capturedAt, 30, nowMs)
    ).length,
    marketingEligible: guests.filter((guest) => guest.marketingEligible).length,
  }

  for (const [key, minimum] of Object.entries(minimums)) {
    const actual = counts[key as keyof typeof counts]
    if (actual < minimum) {
      throw new Error(
        `Fixture coverage for ${key}: expected >= ${minimum}, got ${actual}`
      )
    }
  }
}
