#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/infra/qa/secrets.qa.env}"
QA_WEBHOOK_URL_DEFAULT="https://ca-tummly-qa-api.agreeablewater-62e50314.uksouth.azurecontainerapps.io/api/webhooks/revolut"
SANDBOX_API_BASE="https://sandbox-merchant.revolut.com"
API_VERSION="2026-04-20"

TOTAL_STAGES=8

# Ensure the gitignored QA secrets file exists (do not commit filled values).
# Do not replace a missing full secrets.qa.env with Revolut-only example —
# upsert Revolut/VAT keys into whatever file the operator keeps for ACA.
if [[ ! -f "$ENV_FILE" ]]; then
  touch "$ENV_FILE"
  note "Created empty $ENV_FILE — this wizard only upserts Revolut + VAT keys."
fi

banner "Revolut QA Sandbox (Merchant + test cards)"
note "Created/using $ENV_FILE (gitignored). Never paste Production sk_ keys here."

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Wrong portal: leave CSR / Client ID"
say "Tummly billing uses Merchant API Hosted Checkout — not the developer-portal CSR app."
warn "Do not finish Sandbox authentication (CSR / Client ID) for this wizard."
step "Close or ignore developer.revolut.com → Tummly → Sandbox authentication."
pause "Press Enter when you will use Business Sandbox Merchant API instead."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create / open Revolut Business Sandbox"
say "Sandbox Business is separate from live Business and from Production Merchant."
open_url "https://developer.revolut.com/docs/guides/merchant/test-and-go-live/set-up-sandbox"
open_url "https://sandbox-business.revolut.com/signup"
step "Register a new Sandbox Business account (not your live Business login)."
step "If you already have Sandbox Business, open https://sandbox-business.revolut.com and log in."
step "On verify-email pop-ups, use Skip email verification when Sandbox offers it."
pause "Press Enter when you are logged into Sandbox Business."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sandbox Merchant API secret"
say "Keys live under Merchant → Merchant API (Secret starts with sk_)."
open_url "https://sandbox-business.revolut.com"
step "In Sandbox Business: open Merchant overview."
step "Open Merchant API (gear / APIs → Merchant API — labels vary slightly)."
step "Generate (or reveal) the Sandbox Secret API key. Copy it."
warn "Do not paste a Production secret. Public / Client ID are not used for HPP."
ask_secret Revolut__SecretKey "Paste Sandbox Merchant Secret (sk_…):"
if [[ -z "${Revolut__SecretKey}" ]]; then
  warn "Secret is empty — re-run this stage later."
else
  write_env Revolut__SecretKey "$Revolut__SecretKey"
fi
write_env Revolut__RequireSandboxHost "true"
write_env Revolut__ApiBaseUrl "$SANDBOX_API_BASE"
write_env Revolut__ApiVersion "$API_VERSION"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Seller VAT / legal (QA invoices)"
say "These four fields print on QA TM- PDFs. Use real legal values or clear QA placeholders."
ask TUMMLY_VAT_REGISTRATION_NUMBER "VAT registration number:"
ask TUMMLY_VAT_EFFECTIVE_DATE "VAT effective date (YYYY-MM-DD):"
ask TUMMLY_LEGAL_NAME "Legal entity name:"
ask TUMMLY_REGISTERED_ADDRESS "Registered address (one line):"
write_env TUMMLY_VAT_REGISTRATION_NUMBER "$TUMMLY_VAT_REGISTRATION_NUMBER"
write_env TUMMLY_VAT_EFFECTIVE_DATE "$TUMMLY_VAT_EFFECTIVE_DATE"
write_env TUMMLY_LEGAL_NAME "$TUMMLY_LEGAL_NAME"
write_env TUMMLY_REGISTERED_ADDRESS "$TUMMLY_REGISTERED_ADDRESS"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create eight Sandbox plan variations"
say "Repo script creates pack lookup keys → plan_variation_id on THIS Sandbox account."
PLAN_KEYS=(
  tummly_starter_monthly_gbp_v3
  tummly_starter_annual_gbp_v3
  tummly_growth_monthly_gbp_v3
  tummly_growth_annual_gbp_v3
  tummly_group_monthly_gbp_v3
  tummly_group_annual_gbp_v3
  tummly_group_location_monthly_gbp_v3
  tummly_group_location_annual_gbp_v3
)
OUT_MAP="$(mktemp)"
APPLY_OK=0
if [[ -n "${Revolut__SecretKey:-}" ]] && confirm "Run create-plan-variations.sh --apply now (calls Sandbox Merchant API)?"; then
  export PATH="${HOME}/.dotnet:${PATH}"
  if ! command -v dotnet >/dev/null 2>&1; then
    warn "dotnet not on PATH — paste UUIDs by hand in the next prompts."
  else
    set +e
    REVOLUT_SECRET_KEY="$Revolut__SecretKey" \
      REVOLUT_API_BASE_URL="$SANDBOX_API_BASE" \
      REVOLUT_API_VERSION="$API_VERSION" \
      "$ROOT/scripts/revolut-create-plan-variations/create-plan-variations.sh" --apply \
      --out "$OUT_MAP"
    APPLY_STATUS=$?
    set -e
    if [[ "$APPLY_STATUS" -eq 0 && -s "$OUT_MAP" ]]; then
      APPLY_OK=1
      note "Script wrote variation map to temp file."
      while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" || "$line" == \#* ]] && continue
        key="${line%%=*}"
        val="${line#*=}"
        [[ -n "$key" && -n "$val" ]] && write_env "$key" "$val"
      done < "$OUT_MAP"
    else
      warn "Apply failed or empty map — paste UUIDs manually."
    fi
  fi
fi
rm -f "$OUT_MAP"
if [[ "$APPLY_OK" -ne 1 ]]; then
  say "Paste each Sandbox plan_variation_id (or Enter to keep existing)."
  for pk in "${PLAN_KEYS[@]}"; do
    ask "Revolut__PlanVariations__${pk}" "UUID for ${pk}:"
    eval "val=\${Revolut__PlanVariations__${pk}}"
    write_env "Revolut__PlanVariations__${pk}" "$val"
  done
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Register QA webhook + signing secret"
say "Merchant webhooks are usually created via API (signing_secret shown once)."
ask QA_WEBHOOK_URL "QA webhook URL (Enter = ACA default):"
[[ -z "${QA_WEBHOOK_URL}" ]] && QA_WEBHOOK_URL="$QA_WEBHOOK_URL_DEFAULT"
note "URL: $QA_WEBHOOK_URL"
WEBHOOK_EVENTS='["ORDER_COMPLETED","ORDER_FAILED","ORDER_CANCELLED","ORDER_AUTHORISED","ORDER_PAYMENT_DECLINED","ORDER_PAYMENT_FAILED","SUBSCRIPTION_INITIATED","SUBSCRIPTION_CANCELLED","SUBSCRIPTION_OVERDUE","SUBSCRIPTION_FINISHED","DISPUTE_ACTION_REQUIRED","DISPUTE_UNDER_REVIEW","DISPUTE_WON","DISPUTE_LOST"]'
WH_OK=0
if [[ -n "${Revolut__SecretKey:-}" ]] && confirm "Create webhook now with curl against Sandbox Merchant?"; then
  WH_BODY="$(mktemp)"
  set +e
  HTTP_CODE=$(
    curl -sS -o "$WH_BODY" -w "%{http_code}" \
      -X POST "${SANDBOX_API_BASE}/api/1.0/webhooks" \
      -H "Authorization: Bearer ${Revolut__SecretKey}" \
      -H "Revolut-Api-Version: ${API_VERSION}" \
      -H "Content-Type: application/json" \
      -d "{\"url\":\"${QA_WEBHOOK_URL}\",\"events\":${WEBHOOK_EVENTS}}"
  )
  CURL_STATUS=$?
  set -e
  if [[ "$CURL_STATUS" -eq 0 && "$HTTP_CODE" =~ ^2 ]]; then
    note "HTTP $HTTP_CODE — parsing signing_secret…"
    SIGNING="$(
      python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
print(d.get("signing_secret") or d.get("signingSecret") or "")
' "$WH_BODY" 2>/dev/null || true
    )"
    if [[ -n "$SIGNING" ]]; then
      write_env Revolut__WebhookSigningSecret "$SIGNING"
      WH_OK=1
      note "Webhook id (keep for support): $(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("id",""))' "$WH_BODY" 2>/dev/null || true)"
    else
      warn "Response had no signing_secret — paste it manually."
      note "Body saved hint: open the curl response or re-create in dashboard/API docs."
    fi
  else
    warn "Webhook create failed (HTTP ${HTTP_CODE:-n/a}). Paste signing_secret manually."
    [[ -f "$WH_BODY" ]] && note "Response: $(head -c 400 "$WH_BODY")"
  fi
  rm -f "$WH_BODY"
fi
if [[ "$WH_OK" -ne 1 ]]; then
  open_url "https://developer.revolut.com/docs/merchant/create-webhook"
  step "Create a Sandbox webhook for the QA URL above; copy signing_secret once."
  ask_secret Revolut__WebhookSigningSecret "Paste webhook signing_secret:"
  write_env Revolut__WebhookSigningSecret "$Revolut__WebhookSigningSecret"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Review secrets.qa.env"
say "Confirm the file is complete before ACA apply."
step "Open $ENV_FILE and check Revolut__* + TUMMLY_* are non-empty."
warn "File must stay gitignored. Do not commit it."
pause "Press Enter after you have reviewed the file."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Apply to QA ACA (optional)"
say "This updates Azure Container App env from secrets.qa.env (needs az login)."
if confirm "Run apply-aca-secrets.ps1 now?"; then
  if command -v pwsh >/dev/null 2>&1; then
    (cd "$ROOT/infra/qa" && pwsh -File ./apply-aca-secrets.ps1) || \
      warn "apply-aca-secrets.ps1 failed — run it by hand when ready."
  elif command -v powershell >/dev/null 2>&1; then
    (cd "$ROOT/infra/qa" && powershell -File ./apply-aca-secrets.ps1) || \
      warn "apply-aca-secrets.ps1 failed — run it by hand when ready."
  else
    warn "PowerShell not found. Later: cd infra/qa && ./apply-aca-secrets.ps1"
    SKIPPED+=("ACA apply (run infra/qa/apply-aca-secrets.ps1)")
  fi
  note "After revision is ready: $ROOT/scripts/probe-qa-revolut-sandbox.sh"
  if confirm "Probe /health/revolut on QA now?"; then
    "$ROOT/scripts/probe-qa-revolut-sandbox.sh" || \
      warn "Probe failed — wait for revision, then re-run the probe script."
  fi
else
  SKIPPED+=("ACA apply + probe (see infra/qa/REVOLUT-QA-SANDBOX.md)")
  note "When ready: cd infra/qa && ./apply-aca-secrets.ps1"
  note "Then: ./scripts/probe-qa-revolut-sandbox.sh"
fi

finish
note "Rehearsal matrix + test cards: infra/qa/REVOLUT-QA-SANDBOX.md"
